### ISSUE TITLE
Generate a merged stringtable or report

### ISSUE THREAD

**Issue by 11RDP-LoupVert** [bux578/tabler#13]
The point would be to then be able to find out duplicate entries, within the project but even among several projects.

Ideally, it would generate an xml with filenames in comment, eg.

    
    <Key ID="STR_My_Amazing_Example_InvalidAsset">
      <Czech>Invalid asset type.</Czech>
      <English>Invalid asset type.</English>
      <French>Invalid asset type.</French>
      <German>Invalid asset type.</German>
      <Hungarian>Invalid asset type.</Hungarian>
      <Polish>Invalid asset type.</Polish>
      <Portuguese>Invalid asset type.</Portuguese>
      <Russian>Invalid asset type.</Russian>
      <Spanish>Invalid asset type.</Spanish>
    </Key>

**Comment by bux578** [comment]
Closing this in favor of #39
