### ISSUE TITLE
i18n of the tool itself

### ISSUE THREAD

**Issue by Tourorist** [bux578/tabler#19]
This is more of a cherry on top of the cake kind of feature request, if only for the fact that tabler's UI is fairly self-explanatory and there aren't even that many unique strings, to fully justify the amount of restructuring work that this undertaking might require.

However, if done through the auto-loading stringtable.xml as well, then it could be presented as a demo project for new users to explore available functionality and play with features in a safe environment—provided there is a reset button. :smile:

**Comment by bux578** [comment]
@Tourorist there a some free tools that allow editing resx. I haven't tried any of them.

* http://simpleresxeditor.blogspot.de/
* http://www.zeta-resource-editor.com/index.html

**Comment by bux578** [comment]
you would create `*.ru.resx` files

**Comment by Tourorist** [comment]
I was actually hoping to have tabler's own translations as a live demo. That is, done in such a way that it would come with some of these localization files in non-compiled form, for users to play with and learn the interface. Well, either way, doesn't hurt to have them embedded. :smile:
