### ISSUE TITLE
Tabler does now not show Translation progress graphic when there's nothing left to translate

### ISSUE THREAD

**Issue by Legolasindar** [bux578/tabler#33]
With the actual version of ACE3, in the Tabler if i select Translation Progress this not show any graphic, only the windows in white.
I have last 0.4.2 Tabler version.

**Comment by PabstMirror** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9376747/7630441/a5a177e2-f9fb-11e4-822e-59849f1ac22e.png)

I can still right click the graph area and get in clipboard:
```
Total number of keys: 1026
Total number of missing translations: 0
```

**Comment by Legolasindar** [comment]
I think that having nothing outstanding to translate, so giving a blank window. I expected a normal window with bars to zero or no bars, but with other things.

**Comment by PabstMirror** [comment]
Ya, just delete a line in a stringtable and the graph shows up again.
I guess ACE is so perfect that there's no reason to show the graph :)
