### ISSUE TITLE
add russian translation

### ISSUE THREAD

**Issue by bux578** [bux578/tabler#34]
@Tourorist I have some more work for you :)

https://github.com/bux578/tabler/blob/master/tabler/SettingsForm.ru.resx#L158
and
https://github.com/bux578/tabler/blob/master/tabler/SettingsForm.ru.resx#L164

**Comment by bux578** [comment]
It's a function to remove empty xml nodes from the stringtable.xml

So: 
```
<English>Test</English>
<Russian></Russian>
<German></German>
```
will become
```
<English>Test</English>
```

**Comment by Tourorist** [comment]
Your wish is my command, don @bux578.
![](http://s3.amazonaws.com/rapgenius/1327285110_godfather.jpg)

**Comment by bux578** [comment]
:joy:
