### ISSUE TITLE
Add EOF newline support

### ISSUE THREAD

**Issue by jonpas** [bux578/tabler#41]
Currently if the last line is an empty line tabler will remove it, while other text editors can be configured to add it automatically for nicer Git commits, so there is a clash, adding, removing, adding, removing...

Would be nice if tabler would recognize this and retain it as it is (either there is an empty last line or there isn't), or at least a setting to toggle adding it or removing it if there is one.

**Comment by bux578** [comment]
It's not easily doable with the `XmlWriter` class. Might need to change that to a different class.

**Comment by bux578** [comment]
Any ideas @MaMilaCan ?
