### ISSUE TITLE
Never ending loading

### ISSUE THREAD

**Issue by 56curious** [bux578/tabler#70]
While loading an a folder, it never stopped loading. I was loading from my github directory and then the addon folder itself. While trying to open, it never stopped loading, I also placed a string table in there and then tried again with the same never ending loading.

**Comment by bux** [comment]
Do you have a sample repo I could try that on?

**Comment by 56curious** [comment]
https://github.com/56curious/Sample
Made this, I just clicked the folder as a mod path and it never stopped, left it for a while.

**Comment by bux** [comment]
It instantly loaded for me
![image](https://user-images.githubusercontent.com/1235520/54029180-d5927580-41a7-11e9-90ae-cf7aafd07c7f.png)


Maybe try downloading tabler anew?

**Comment by bux** [comment]
@56curious any updates?
