### ISSUE TITLE
Duplicated progress bars

### ISSUE THREAD

**Issue by R3voA3** [bux578/tabler#71]
![image](https://user-images.githubusercontent.com/17484252/57840374-ca238200-77c8-11e9-9c6b-6b5a2be9402b.png)

Steps to reproduce:
1. Open file with errors
2. Close the error message
3. Open the file again
-> Progress bar was duplicated

**Comment by R3voA3** [comment]
They also stay if the whole application window is closed.
![image](https://user-images.githubusercontent.com/17484252/57840573-2be3ec00-77c9-11e9-9cc3-db81c32dd39e.png)

**Comment by MaMilaCan** [comment]
I fixed this. 
Although @bux needs to approve :D

**Comment by bux** [comment]
@MaMilaCan ❤️ 
Did you open a Pull Request yet?
